version: '3.8'

services:
    # dashboard:
    #     build: ./dashboard
    #     networks:
    #         - TPnet
    #     restart: unless-stopped
    # api:
    #     build: ./backend
    #     networks:
    #         - TPnet
    #     restart: unless-stopped
    counter:
        build: ./counter
        networks:
            - TPnet
        restart: unless-stopped
    test:
        build: ./test
        networks:
            - TPnet
        restart: unless-stopped

networks:
    TPnet:
        driver: bridge
