version: '3.8'

services:
    dashboard:
        build: ./dashboard
        container_name: dashboard
        networks:
            - TPnet
        restart: unless-stopped
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8000/" ]
            interval: 3s
            timeout: 3s
            retries: 5
            start_period: 2s
    # api:
    #     build: ./backend
    #     networks:
    #         - TPnet
    #     restart: unless-stopped
    # counter:
    #     build: ./counter
    #     networks:
    #         - TPnet
    #     restart: unless-stopped
    test:
        build: ./test
        container_name: test
        networks:
            - TPnet
        restart: unless-stopped
        depends_on:
            dashboard:
                condition: service_healthy

networks:
    TPnet:
        driver: bridge
